<script src="resources/js/jquery.min.js" type="text/javascript"></script>
<script src="resources/js/tether.min.js" type="text/javascript"></script>
<script src="resources/js/bootstrap.min.js" type="text/javascript"></script>
<script src="resources/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
<script src="resources/js/unison.min.js" type="text/javascript"></script>
<script src="resources/js/blockUI.min.js" type="text/javascript"></script>
<script src="resources/js/jquery.matchHeight-min.js" type="text/javascript"></script>
<script src="resources/js/screenfull.min.js" type="text/javascript"></script>
<script src="resources/js/pace.min.js" type="text/javascript"></script>
<script src="resources/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="resources/js/app-menu.js" type="text/javascript"></script>
<script src="resources/js/app.js" type="text/javascript"></script>
